version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx500m
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn -s .circleci/settings.xml de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Denforce-project-quality
      - run: mvn -s .circleci/settings.xml org.apache.maven.plugins:maven-dependency-plugin:resolve-plugins -Denforce-project-quality

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn -B -o -s .circleci/settings.xml clean compile javadoc:jar install -Denforce-project-quality

      - store_test_results:
          path: coeus-api-all/target/surefire-reports