/*
 * Kuali Coeus, a comprehensive research administration system for higher education.
 * 
 * Copyright 2005-2015 Kuali, Inc.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.kuali.coeus.propdev.api.attachment;

import java.util.List;


public interface NarrativeService {

    /**
     * Given a collection of narratives, each narratives that was "auto-generated" will be deleted
     * from the proposal development system of record.
     *
     * @param narratives the collection of narratives.  Cannot be null.
     * @throws IllegalArgumentException if narratives collection is null
     */
    void deleteAutoGeneratedNarratives(List<? extends NarrativeContract> narratives);

    /**
     * Checks if a narrative is "auto-generated".
     * @param narrative the narrative.  Cannot be null.
     * @return true if the narrative is "auto-generated"
     * @throws IllegalArgumentException if narrative is null
     */
    boolean isAutoGeneratedNarrative(NarrativeContract narrative);

    /**
     * This method creates a system generated narrative.  Save it to the system of record.
     * None of the parameters can be null or blank.
     * @param proposalNumber the proposal number which the narrative is associated with.  Cannot be blank.
     * @param narrativeTypeCode  the narrative type code.  Cannot be blank.
     * @param attachmentData the attachment data.  Cannot be blank (null or empty array)
     * @param attachmentName the name of the attachment.  Cannot be blank.
     * @param comments the comments on the narrative.  Cannot be blank.
     * @return the created and saved narrative.  Will not return null.
     */
    NarrativeContract createSystemGeneratedNarrative(String proposalNumber, String narrativeTypeCode, byte[] attachmentData, String attachmentName, String comments);

    /**
     * Given a collection of narratives, each narratives that was "system-generated" will be deleted
     * from the proposal development system of record.
     *
     * @param narratives the collection of narratives.  Cannot be null.
     * @throws IllegalArgumentException if narratives collection is null
     */
    void deleteSystemGeneratedNarratives(List<? extends NarrativeContract> narratives);

    /**
     * Checks if a narrative is "system-generated".
     * @param narrative the narrative.  Cannot be null.
     * @return true if the narrative is "auto-generated"
     * @throws IllegalArgumentException if narrative is null
     */
    boolean isSystemGeneratedNarrative(NarrativeContract narrative);
}
